name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the version value
        id: version
        run: |
          version=$(jq '.version' package.json | sed "s/\"//g")
          echo "PKG_VERSION=v$version" >> "$GITHUB_OUTPUT"
      # PREPARE DOCKER ENVIRONMENT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            rodcordeiro/escriba-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha  
      # BUILD AND PUSH DOCKER IMAGES
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          push: true
          tags: rodcordeiro/escriba-api:latest,rodcordeiro/escriba-api:${{ steps.version.outputs.PKG_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
      
  